name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    name: Release

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - name: Build
        run: yarn build

      - name: Setup Git remote
        run: ./scripts/setup-git-ci.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Add schema repo
        run: |
          pushd ..
          git clone https://x-access-token:${GITHUB_TOKEN}@github.com/vega/schema.git
          popd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check NPM deployment
        run: ./scripts/check-npm.sh

      - name: Publish to NPM registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
      - name: Publish to GitHub registry
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish website
        run: ./scripts/deploy-site.sh

      - name: Publish schema
        run: ./scripts/deploy-schema.sh
